# Generated by Django 2.2.10 on 2023-01-30 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatdata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformportal',
            name='sequence',
            field=models.IntegerField(default=1),
        ),
    ]
