# Generated by Django 2.2.10 on 2023-02-01 21:14

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatdata', '0002_platformportal_sequence'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemPortal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('more_details', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SystemPortal',
                'verbose_name_plural': 'SystemPortals',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='platformportal',
            name='link',
        ),
        migrations.AddField(
            model_name='platformportal',
            name='system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platformportals', to='chatdata.SystemPortal'),
        ),
    ]
